[project]
name = "ftl-tools"
version = "0.2.0"
dependencies = [
    "faster_than_light",
    "rich",
    "linode_api4",
    "click",
    "pyyaml",
    "ftl_automation",
]

[tool.setuptools]
packages = ['ftl_tools', 'ftl_tools.tools']

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
