[project]
name = "ftl-tools"
version = "0.2.0"
dependencies = [
    "smolagents[litellm]==1.9.2",
    "ftlagents",
    "rich",
    "linode_api4",
]

[tool.setuptools]
packages = ['ftl_tools', 'ftl_tools.tools']

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
